Repository 79gun79/FiveCoders, pull requests merged in 2025-05, with the labels that each got.

#3 Feature/post
  src/App.tsx
  src/components/CommentForm.tsx
  src/components/CommentList.tsx
  src/components/IsLoggedInModal.tsx
  src/components/PostList.tsx
  src/css/font.css
  src/css/index.css
  src/css/root.css
  src/pages/Channel.tsx
  src/pages/Login.tsx
  src/pages/SignUp.tsx
  src/types/commentsData.ts
  src/types/post.d.ts
  src/types/postsData.ts
Labels: 🎉feature, 🎨 design

#5 Feature/sidebar
  src/App.tsx
  src/assets/channelImg.svg
  src/assets/globe.svg
  src/assets/home.svg
  src/components/Sidebar.tsx
  src/components/ValidateInput.tsx
  src/css/root.css
  src/types/channel.d.ts
Labels: 🎉feature, 🎨 design

#6 ✨ feat : router 추가 및 로그인 비밀 번호 input 재설정
  src/App.tsx
  src/components/PasswordInput.tsx
  src/components/ValidateInput.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/NotFound.tsx
  src/pages/Post.tsx
  src/pages/SignUp.tsx
  src/router.tsx
  src/utils/validators.ts
Labels: 🎉feature

#7 Feature/createPost
  index.html
  package.json
  public/gammue.ico
  src/App.tsx
  src/assets/channelImg.svg
  src/assets/fcOnline.jpg
  src/assets/globe.svg
  src/assets/home.svg
  src/components/Button.tsx
  src/components/ChooseCommunity.tsx
  src/components/CommentForm.tsx
  src/components/CommentList.tsx
  src/components/Input.tsx
  src/components/IsLoggedInModal.tsx
  src/components/PasswordInput.tsx
  src/components/PostEditor.tsx
  src/components/PostList.tsx
  src/components/ProtectedRoute.tsx
  src/components/Sidebar.tsx
  src/components/ValidateInput.tsx
  src/css/font.css
  src/css/index.css
  src/css/root.css
  src/pages/Channel.tsx
  src/pages/CreatePost.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/NotFound.tsx
  src/pages/Post.tsx
  src/pages/SignUp.tsx
  src/router.tsx
  src/types/channel.d.ts
  src/types/commentsData.ts
  src/types/post.d.ts
  src/types/postsData.ts
  src/utils/validators.ts
Labels: 🎉feature, 🎨 design

#10 Feature/search
  src/assets/GammueLogo.png
  src/components/Header.tsx
  src/components/HeaderLogin.tsx
  src/components/HeaderNotLogin.tsx
  src/pages/Search.tsx
  src/router.tsx
  src/types/user.d.ts
Labels: 🎉feature, 🔧 fix, 🎨 design

#11 Feature/axios
  src/assets/steam-big.svg
  src/assets/steam-small.svg
  src/components/SteamCard.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/SignUp.tsx
  src/services/axios.ts
  src/stores/authStore.ts
  vite.config.ts
Labels: 🎉feature

#12 Feature/createPost
  index.html
  package.json
  src/App.tsx
  src/assets/fcOnline.jpg
  src/components/ChooseCommunity.tsx
  src/components/CommentForm.tsx
  src/components/CommentList.tsx
  src/components/Header.tsx
  src/components/HeaderNotLogin.tsx
  src/components/IsLoggedInModal.tsx
  src/components/PostEditor.tsx
  src/components/PostList.tsx
  src/css/index.css
  src/css/root.css
  src/pages/Channel.tsx
  src/pages/Content.tsx
  src/pages/CreatePost.tsx
  src/pages/Login.tsx
  src/pages/Search.tsx
  src/pages/SignUp.tsx
  src/router.tsx
  src/types/channel.d.ts
  src/types/commentsData.ts
  src/types/postsData.ts
Labels: 🎉feature, 🎨 design

#15 Feature : 404page
  src/components/SteamCard.tsx
  src/css/notFount.module.css
  src/pages/Home.tsx
  src/pages/NotFound.tsx
Labels: 🎉feature, 🎨 design

#16 feature/search
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/Sidebar.tsx
  src/css/index.css
  src/data/dummyChannels.ts
  src/pages/ChannelList.tsx
  src/pages/Search.tsx
  src/router.tsx
Labels: 🎉feature, 🎨 design

#17 Feature/sidebar
  src/components/IsLoggedInModal.tsx
  src/components/Sidebar.tsx
  src/services/channelApi.ts
  src/utils/localSubscribe.ts
Labels: 🎉feature, 🎨 design

#18 Feature/crud post
  .prettierignore
  .prettierrc
  package.json
  src/App.tsx
  src/components/Button.tsx
  src/components/ChannelCard.tsx
  src/components/ChooseCommunity.tsx
  src/components/CommentForm.tsx
  src/components/CommentList.tsx
  src/components/Header.tsx
  src/components/HeaderLogin.tsx
  src/components/HeaderNotLogin.tsx
  src/components/Input.tsx
  src/components/IsLoggedInModal.tsx
  src/components/PasswordInput.tsx
  src/components/PostEditor.tsx
  src/components/PostList.tsx
  src/components/Sidebar.tsx
  src/components/ValidateInput.tsx
  src/css/font.css
  src/css/index.css
  src/css/notFount.module.css
  src/css/tailwind.css
  src/data/commentsData.ts
  src/data/dummyChannels.ts
  src/data/postsData.ts
  src/main.tsx
  src/pages/Channel.tsx
  src/pages/ChannelList.tsx
  src/pages/Content.tsx
  src/pages/CreatePost.tsx
  src/pages/Home.tsx
  src/pages/Layout.tsx
  src/pages/Login.tsx
  src/pages/NotFound.tsx
  src/pages/Search.tsx
  src/pages/SignUp.tsx
  src/router.tsx
  src/services/axios.ts
  src/services/channelApi.ts
  src/stores/authStore.ts
  src/stores/commentStore.ts
  src/stores/postStore.ts
  src/types/channel.d.ts
  src/types/commentsData.ts
  src/types/post.d.ts
  src/utils/localSubscribe.ts
  src/utils/validators.ts
Labels: 🎉feature, 🎨 design, ⚙️ setting

#19 Feature/my-page
  .prettierignore
  src/assets/icons/Like.svg
  src/assets/icons/Reply.svg
  src/assets/icons/Setting.svg
  src/assets/imgs/기본 프로필.png
  src/components/MyComment.tsx
  src/components/MyInfo.tsx
  src/components/MyPost.tsx
  src/components/ProfileUpload.tsx
  src/components/SettingInput.tsx
  src/components/ValidateNickNameInput .tsx
  src/components/ValidatePasswordInput.tsx
  src/css/index.css
  src/data/CommentData.ts
  src/data/PostData.ts
  src/data/UserData.ts
  src/pages/MyPage.tsx
  src/pages/ProfileSetting.tsx
  src/router.tsx
  src/types/profile.d.ts
  src/utils/validators.ts
Labels: 🎉feature, 🎨 design

#20 Feature/search
  src/assets/GammueLogo.png
  src/components/Header.tsx
  src/components/HeaderNotLogin.tsx
  src/components/PostList.tsx
  src/components/SearchPost.tsx
  src/pages/Search.tsx
Labels: 🎉feature, 🎨 design

#21 Feature/steam api
  .prettierignore
  src/components/SteamCard.tsx
  src/pages/Home.tsx
  src/pages/Post.tsx
  src/pages/SignUp.tsx
  src/services/steamApi.ts
  src/types/commentsData.ts
  src/types/postsData.ts
Labels: 🎉feature, 🎨 design

#22 Feature/post channel
  src/components/ChooseCommunity.tsx
  src/components/CommentForm.tsx
  src/components/CommentList.tsx
  src/components/PostEditor.tsx
  src/components/PostList.tsx
  src/components/Sidebar.tsx
  src/css/index.css
  src/data/commentsData.ts
  src/data/dummyChannels.ts
  src/data/postsData.ts
  src/pages/Channel.tsx
  src/pages/ChannelList.tsx
  src/pages/ChannelPage.tsx
  src/pages/Content.tsx
  src/pages/CreatePost.tsx
  src/router.tsx
  src/stores/channelStore.ts
  src/stores/postStore.ts
  src/types/post.d.ts
Labels: 🎉feature

#23 Feature/my page
  package.json
  src/components/Toast.tsx
  src/components/Tooltip.tsx
  src/components/ValidatePasswordInput.tsx
  src/css/index.css
  src/data/dfAPI.ts
  src/pages/ProfileSetting.tsx
  src/types/profile.d.ts
Labels: 🎉feature, 🎨 design

#26 Feature/my page
  src/assets/던파로고.png
  src/assets/던파로고미니.png
  src/components/DFCard.tsx
  src/components/MyComment.tsx
  src/components/MyInfo.tsx
  src/components/MyPost.tsx
  src/components/ProfileUpload.tsx
  src/data/dfAPI.ts
  src/pages/Home.tsx
  src/pages/MyPage.tsx
  src/pages/ProfileSetting.tsx
  src/services/UserAPI.ts
  src/services/dfAPI.ts
  src/types/profile.d.ts
  src/utils/validators.ts
  vite.config.ts
Labels: 🔧 fix, 🎨 design

#27 Feature/notification
  src/components/ChannelCard.tsx
  src/components/Header.tsx
  src/components/HeaderLogin.tsx
  src/components/IsLoggedInModal.tsx
  src/components/NotificationCard.tsx
  src/components/NotificationDropdown.tsx
  src/data/dummyChannels.ts
  src/pages/ChannelList.tsx
  src/pages/Layout.tsx
  src/pages/MyPage.tsx
  src/pages/Search.tsx
  src/types/channel.d.ts
  src/types/notification.d.ts
  src/utils/validators.ts
Labels: 🎉feature, 🎨 design, 🧹 refactor

#30 Feature/post api
  src/components/ChooseCommunity.tsx
  src/components/Header.tsx
  src/components/HeaderLogin.tsx
  src/components/IsLoggedInModal.tsx
  src/components/NotificationCard.tsx
  src/components/NotificationDropdown.tsx
  src/components/PostComponent.tsx
  src/components/PostList.tsx
  src/components/ProfileUpload.tsx
  src/data/channelData.ts
  src/data/dummyChannels.ts
  src/pages/Channel.tsx
  src/pages/ChannelPage.tsx
  src/pages/CreatePost.tsx
  src/pages/Home.tsx
  src/pages/Layout.tsx
  src/pages/MyPage.tsx
  src/pages/Search.tsx
  src/services/axios.ts
  src/stores/commentStore.ts
  src/stores/postStore.ts
  src/types/channel.d.ts
  src/types/commentsData.ts
  src/types/notification.d.ts
  src/types/post.d.ts
  src/types/user.d.ts
  src/utils/post.ts
Labels: 🎉feature

#31 Feature/my page
  src/assets/던파로고.png
  src/assets/명성치.png
  src/assets/헨돈마이어.png
  src/components/DFCard.tsx
  src/components/ProfileUpload.tsx
  src/pages/MyPage.tsx
  src/pages/ProfileSetting.tsx
Labels: 🎉feature

#34 Feature/post image
  src/components/PostComponent.tsx
  src/components/PostEditor.tsx
  src/components/SearchPost.tsx
  src/components/Toast.tsx
  src/css/index.css
  src/data/channelData.ts
  src/main.tsx
  src/pages/CreatePost.tsx
  src/pages/Search.tsx
  src/pages/UpdatePost.tsx
  src/utils/customToast.ts
Labels: 🎉feature

#36 Feature/my page
  src/components/MyComment.tsx
  src/components/MyPost.tsx
  src/components/ProfileUpload.tsx
  src/data/UserData.ts
  src/pages/MyPage.tsx
  src/pages/ProfileSetting.tsx
  src/types/profile.d.ts
Labels: 🎉feature, 🎨 design

#37 ✨ 로그아웃 기능 추가
  src/components/HeaderLogin.tsx
  src/utils/post.ts
Labels: 🎉feature

#38 Feature/post toast
  src/components/MyPost.tsx
  src/components/PostComponent.tsx
  src/components/PostEditor.tsx
  src/components/ProfileUpload.tsx
  src/data/channelData.ts
  src/main.tsx
  src/pages/ChannelList.tsx
  src/pages/CreatePost.tsx
  src/pages/Layout.tsx
  src/pages/UpdatePost.tsx
  src/utils/customConfirm.tsx
  src/utils/customToast.ts
Labels: 🎨 design

#40 Feature/dfapi
  src/components/DFCard.tsx
  src/pages/Home.tsx
  src/services/dfAPI.ts
Labels: 🎉feature, 🎨 design

#43 Feature/channel api
  src/components/ChannelCard.tsx
  src/components/CreateChannelForm.tsx
  src/components/HeaderLogin.tsx
  src/components/IsLoggedInModal.tsx
  src/pages/ChannelList.tsx
  src/pages/Login.tsx
  src/services/authApi.ts
  src/services/channelApi.ts
  src/stores/authStore.ts
  src/types/channel.d.ts
Labels: 🎉feature, 🔧 fix

#39 Feature/home
  src/assets/icons/Like.svg
  src/assets/icons/Reply.svg
  src/assets/icons/confetti.svg
  src/assets/icons/joystick.svg
  src/components/DiscordCard.tsx
  src/components/GameDropdown.tsx
  src/components/SteamCard.tsx
  src/pages/Home.tsx
Labels: 🎉feature, 🎨 design

#45 Feature/comment-API
  src/components/CommentForm.tsx
  src/components/CommentList.tsx
  src/components/PostComponent.tsx
  src/components/PostList.tsx
  src/components/SearchPost.tsx
  src/css/index.css
  src/stores/refreshStore.ts
  src/types/post.d.ts
  src/types/user.d.ts
Labels: 🎉feature, 🎨 design

#41 Feature/my page
  src/components/HeaderLogin.tsx
  src/components/MyComment.tsx
  src/components/MyPost.tsx
  src/components/ProfileUpload.tsx
  src/css/index.css
  src/pages/MyPage.tsx
  src/pages/ProfileSetting.tsx
  src/pages/Search.tsx
  src/router.tsx
  src/stores/imageStore.ts
Labels: 🎉feature, 🔧 fix

#46 Feature/likes
  src/components/ChannelCard.tsx
  src/components/ChooseCommunity.tsx
  src/components/CreateChannelForm.tsx
  src/components/IsLoggedInModal.tsx
  src/components/PostComponent.tsx
  src/components/Sidebar.tsx
  src/pages/Channel.tsx
  src/pages/ChannelList.tsx
  src/pages/ChannelPage.tsx
  src/pages/CreatePost.tsx
  src/pages/Login.tsx
  src/pages/Search.tsx
  src/pages/UpdatePost.tsx
  src/services/authApi.ts
  src/services/channelApi.ts
  src/services/likesApi.ts
  src/stores/authStore.ts
  src/types/channel.d.ts
  src/types/like.d.ts
  src/types/post.d.ts
  src/utils/imageConverter.ts
  src/utils/stateLike.tsx
Labels: 🎉feature, 🔧 fix

#47 feature/comment-api
  src/components/CommentList.tsx
  src/utils/customConfirm.tsx
  src/utils/stateLike.tsx
Labels: 🎉feature

#48 Feature/lieks api
  src/components/CommentForm.tsx
  src/components/PostComponent.tsx
  src/data/channelData.ts
  src/data/commentsData.ts
  src/data/dummyChannels.ts
  src/data/postsData.ts
  src/services/UserAPI.ts
  src/stores/commentStore.ts
  src/types/channel.d.ts
  src/utils/customToast.ts
  src/utils/stateLike.tsx
Labels: 🔧 fix, 🧹 refactor

#50 feature/loading
  index.html
  src/components/PostList.tsx
  src/css/font.css
  src/pages/Channel.tsx
  src/pages/ChannelList.tsx
  src/pages/ChannelPage.tsx
  src/pages/Search.tsx
Labels: 🔧 fix, 🎨 design

#49 Feature/sidebar
  src/App.tsx
  src/components/ChannelCard.tsx
  src/components/HeaderNotLogin.tsx
  src/components/Sidebar.tsx
  src/components/UserList.tsx
  src/pages/ChannelList.tsx
  src/pages/ChannelPage.tsx
  src/services/discordApi.ts
  src/stores/channelStore.ts
  src/stores/subscriptionStore.ts
  src/utils/channelIndexMapping.ts
Labels: 🎉feature, 🧹 refactor

#51 Feature/user post
  src/components/HeaderLogin.tsx
  src/components/MyComment.tsx
  src/components/MyPost.tsx
  src/components/PostComponent.tsx
  src/components/PostList.tsx
  src/pages/MyPage.tsx
  src/services/postApi.ts
  src/types/comment.d.ts
  src/types/post.d.ts
  src/types/profile.d.ts
  src/types/user.d.ts
Labels: 🎉feature, 🎨 design

#52 Feature/my page
  src/components/HeaderLogin.tsx
  src/components/MyPost.tsx
  src/components/ProfileUpload.tsx
  src/pages/ProfileSetting.tsx
  src/services/likesApi.ts
  src/stores/imageStore.ts
  src/types/profile.d.ts
Labels: 🚑 hotfix, 🧹 refactor

#53 Feature/sidebar
  src/assets/imgs/defaultProfileImg.png
  src/components/MyComment.tsx
  src/components/MyPost.tsx
  src/components/ProfileUpload.tsx
  src/components/Sidebar.tsx
  src/components/UserList.tsx
  src/pages/MyPage.tsx
  src/pages/ProfileSetting.tsx
  src/services/UserAPI.ts
  src/types/user.d.ts
Labels: 🎉feature, 🎨 design

#55 feature/loading
  src/components/CommentForm.tsx
  src/utils/stateLike.tsx
Labels: 🔧 fix

#59 💄 style : my Page ui 수정
  src/components/MyInfo.tsx
  src/components/MyPost.tsx
  src/css/index.css
  src/pages/MyPage.tsx
Labels: 🎨 design

#61 zap/manyContents
  src/components/MyComment.tsx
  src/components/MyPost.tsx
  src/components/SearchPost.tsx
Labels: 🎨 design

#62 feature/search
  src/components/Header.tsx
  src/pages/Search.tsx
Labels: 🎨 design

#63 Feature/sidebar
  src/components/Sidebar.tsx
  src/components/UserList.tsx
  src/css/index.css
  src/pages/Home.tsx
Labels: 🎨 design

#60 Feature/my page
  src/components/DFCard.tsx
  src/components/HeaderLogin.tsx
  src/components/IsLoggedInModal.tsx
  src/components/ProfileUpload.tsx
  src/components/Sidebar.tsx
  src/components/UserList.tsx
  src/pages/Home.tsx
  src/pages/ProfileSetting.tsx
Labels: 🧹 refactor

#64 💄 style : login, signup bg 추가 및 pavicon 변경
  f
  public/gammue.ico
  src/assets/imgs/tile.png
  src/pages/Login.tsx
  src/pages/SignUp.tsx
Labels: 🎨 design

#67 ✨ feat: 알림 클릭 시 바로가기
  src/components/MyComment.tsx
  src/components/MyPost.tsx
  src/components/NotificationCard.tsx
Labels: 🎉feature

#71 Feature/my page
  src/assets/170824_NeopleOpenAPI_LogoGuide.jpg
  src/assets/기술표기_세로형_color.png
  src/components/Footer.tsx
  src/pages/Home.tsx
  src/pages/Layout.tsx
Labels: 🎨 design
